const { v4: uuid } = require('uuid');
const mysql = require("mysql2/promise");

const maleNameSurname = [
    'Abdon Nowak',
    'Abel Kowalski',
    'Abelard Wiśniewski',
    'Abraham Wójcik',
    'Achilles Kowalczyk',
    'Adam Kamiński',
    'Adelard Lewandowski',
    'Adnan Zieliński',
    'Adrian Woźniak',
    'Agapit Szymański',
    'Agaton Dąbrowski',
    'Agrypin Kozłowski',
    'Ajdin Jankowski',
    'Albert Mazur',
    'Alan Wojciechowski',
    'Albin Kwiatkowski',
    'Albrecht Krawczyk',
    'Aleks Kaczmarek',
    'Aleksander Piotrowski',
    'Aleksy Grabowski',
    'Alfons Zając',
    'Alfred Król',
    'Alojzy Pawłowski',
    'Alwin Michalski',
    'Amadeusz Wróbel',
    'Ambroży Jabłoński',
    'Anastazy Wieczorek',
    'Ananiasz Nowakowski',
    'Anatol Majewski',
    'Andrzej Olszewski',
    'Anioł Stępień',
    'Annasz Jaworski',
    'Antoni Dudek',
    'Antonin Adamczyk',
    'Antonius Malinowski',
    'Anzelm Pawlak',
    'Apollo Górski',
    'Apoloniusz Sikora',
    'Ariel Nowicki',
    'Arkadiusz Witkowski',
    'Arkady Walczak',
    'Arnold Baran',
    'Artur Rutkowski',
    'August Michalak',
    'Augustyn Szewczyk',
    'Aurelian Ostrowski',
    'Baldwin Tomaszewski',
    'Baltazar Zalewski',
    'Barabasz Wróblewski',
    'Barnim Pietrzak',
    'Bartłomiej Jasiński',
    'Bartosz Marciniak',
    'Bazyli Bąk',
    'Beat Sadowski',
    'Benedykt Zawadzki',
    'Beniamin Jakubowski',
    'Benon Duda',
    'Bernard Wilk',
    'Bert Chmielewski',
    'Błażej Włodarczyk',
    'Bodosław Borkowski',
    'Bogdał Szczepański',
    'Bogdan Sokołowski',
    'Boguchwał Sawicki',
    'Bogumił Lis',
    'Bogumir Kucharski',
    'Bogusław Mazurek',
    'Bogusz Kalinowski',
    'Bolebor Kubiak',
    'Bolelut Maciejewski',
    'Bolesław Wysocki',
    'Bonawentura Kaźmierczak',
    'Bonifacy Kołodziej',
    'Borys Czarnecki',
    'Borysław Sobczak',
    'Borzywoj Konieczny',
    'Bożan Krupa',
    'Bożidar Mróz',
    'Bożydar Głowacki',
    'Bożimir Krajewski',
    'Bromir Urbański',
    'Bronisław Zakrzewski',
    'Bruno Wasilewski',
    'Brunon Laskowski',
    'Budzisław Sikorski',
    'Cecyl Ziółkowski',
    'Cecylian Gajewski',
    'Celestyn Makowski',
    'Cezar Szulc',
    'Cezary Kaczmarczyk',
    'Chociemir Szymczak',
    'Chrystian Brzeziński',
    'Chwalibóg Baranowski',
    'Chwalimir Przybylski',
    'Chwalisław Kania',
    'Cichosław Błaszczyk',
    'Ciechosław Janik',
    'Cyprian Szczepaniak',
    'Cyryl Borowski',
    'Czesław Adamski',
    'Dajmir Górecki',
    'Dal Chojnacki',
    'Dalbor Mucha',
    'Damazy Kozak',
    'Damian Kozioł',
    'Daniel Leszczyński',
    'Danisław Mikołajczyk',
    'Danko Czerwiński',
    'Dargomir Lipiński',
    'Dargosław Andrzejewski',
    'Dariusz Zięba',
    'Darwit Kowalewski',
    'Dawid Wesołowski',
    'Denis Cieślak',
    'Derwit Jarosz',
    'Dionizy Kowalik',
    'Dobiesław Musiał',
    'Dobrogost Kołodziejczyk',
    'Dobrosław Kopeć',
    'Domasław Markowski',
    'Dominik Brzozowski',
    'Donald Żak',
    'Donat Piątek',
    'Dorian Kurek',
    'Duszan Domański',
    'Dymitr Nowacki',
    'Dyter Pawlik',
    'Dzwonimierz Wójtowicz',
    'Dżamil Tomczyk',
    'Dżan Orłowski',
    'Dżem Tomczak',
    'Dżemil Ciesielski',
    'Edgar Wawrzyniak',
    'Edmund Kot',
    'Edward Polak',
    'Edwin Sowa',
    'Efraim Markiewicz',
    'Efrem Kruk',
    'Eliasz Wolski',
    'Eligiusz Stasiak',
    'Eliot Jastrzębski',
    'Emanuel Urbaniak',
    'Emil Karpiński',
    'Emir Łuczak',
    'Erazm Stankiewicz',
    'Ernest Piasecki',
    'Erwin Klimek',
    'Eugeniusz Wierzbicki',
    'Eryk Nawrocki',
    'Ewald Gajda',
    'Ewaryst Czajkowski',
    'Ezaw Dziedzic',
    'Ezechiel Bielecki',
    'Fabian Stefański',
    'Farid Madej',
    'Faris Janicki',
    'Faustyn Bednarek',
    'Felicjan Milewski',
    'Feliks Leśniak',
    'Ferdynand Sosnowski',
    'Filip Skiba',
    'Florentyn Kowal',
    'Florian Jóźwiak',
    'Fortunat Majchrzak',
    'Franciszek Maj',
    'Fryc Śliwiński',
    'Fryderyk Socha',
    'Gabriel Małecki',
    'Gabor Domagała',
    'Gaj Bednarczyk',
    'Gardomir Wrona',
    'Gaweł Marek',
    'Gerard Urban',
    'Gerwazy Kasprzak',
    'Gilbert Pająk',
    'Ginter Dobrowolski',
    'Gniewomir Matuszewski',
    'Gniewosz Ratajczak',
    'Godfryg Olejniczak',
    'Godfryd Michalik',
    'Godzisław Świątek',
    'Gościsław Kurowski',
    'Gracjan Orzechowski',
    'Grodzisław Wilczyński',
    'Grzegorz Romanowski',
    'Grzymisław Olejnik',
    'Gustaw Łukasik',
    'Gwalbert Owczarek',
    'Gwido Grzelak',
    'Gwidon Sroka',
    'Hadrian Barański',
    'Hamza Rogowski',
    'Hanusz Mazurkiewicz',
    'Hasan Bukowski',
    'Hektor Kosiński',
    'Heliodor Kędzierski',
    'Henryk Sobolewski',
    'Herakles Bednarz',
    'Herbert Marszałek',
    'Herman Zych',
    'Hermes Matusiak',
    'Hiacynt Kozieł',
    'Hieronim Sobczyk',
    'Hilary Skowroński',
    'Hipolit Marcinkowski',
    'Honorat Kasprzyk',
    'Horacy Białek',
    'Hubert Chrzanowski',
    'Hugo Świderski',
    'Hugon Rybak',
    'Husajn Kwiecień',
    'Idzi Lisowski',
    'Ignacy Witek',
    'Igor Bednarski',
    'Ildefons Paluch',
    'Inocenty Czajka',
    'Ireneusz Pluta',
    'Iwan Turek',
    'Iwo Chmiel',
    'Iwon Kuczyński',
    'Izajasz Jędrzejewski',
    'Izydor Muszyński',
    'Jacek Morawski',
    'Jacenty Grzybowski',
    'Jakub Janiszewski',
    'Jan Kaczor',
    'January Marczak',
    'Janusz Marzec',
    'Jarad Śliwa',
    'Jaromir Małek',
    'Jaropełk Piekarski',
    'Jarosław Kubicki',
    'Jarowit Szczęsny',
    'Jeremiasz Przybysz',
    'Jerzy Żukowski',
    'Jędrzej Gołębiewski',
    'Joachim Osiński',
    'Jona Stefaniak',
    'Jonasz Krzemiński',
    'Jonatan Kulesza',
    'Jozafat Janowski',
    'Józef Lech',
    'Józefat Biernacki',
    'Julian Szydłowski',
    'Juliusz Kacprzak',
    'Jur Banach',
    'Juri Serafin',
    'Justyn Góra',
    'Justynian Czaja',
    'Jasuf Michałowski',
    'Kacper Smoliński',
    'Kain Staniszewski',
    'Kajetan Murawski',
    'Kajfasz Pietrzyk',
    'Kajusz Kujawa',
    'Kamil Popławski',
    'Kanimir Stachowiak',
    'Karol Lewicki',
    'Kasjusz Rak',
    'Kasper Żurek',
    'Kastor Dębski',
    'Kazimierz Górka',
    'Kemal Cieślik',
    'Kilian Piątkowski',
    'Klaudiusz Czech',
    'Klemens Banaś',
    'Kochan Zawada',
    'Kondrat Rudnicki',
    'Konrad Matysiak',
    'Konradyn Górny',
    'Konstancjusz Podgórski',
    'Konstanty Sowiński',
    'Konstantyn Gołębiowski',
    'Kordian Klimczak',
    'Kornel-Korni Karczewski',
    'Korneli Żurawski',
    'Korneliusz Rosiński',
    'Kosma Czyż',
    'Kryspin Niemiec',
    'Krystian Skrzypczak',
    'Krystyn Kuś',
    'Krzesimir Godlewski',
    'Krzesisław Augustyniak',
    'Krzysztof Bieniek',
    'Ksawery Grochowski',
    'Kwiatosław Ptak',
    'Kwietosław Panek',
    'Lambert Gruszka',
    'Laurencjusz Komorowski',
    'Lech Krawiec',
    'Lechosław Gil',
    'Lenart Różański',
    'Leo Winiarski',
    'Leon Siwek',
    'Leokadiusz Drozd',
    'Leonard Słowik',
    'Leopold Grzyb',
    'Lesław Konopka',
    'Leszek Leśniewski',
    'Lew Kłos',
    'Longin Cybulski',
    'Lubisław Szczepanik',
    'Lubogost Graczyk',
    'Lubomił Przybyła',
    'Lubomir Krzyżanowski',
    'Luborad Młynarczyk',
    'Lubosław Mielczarek',
    'Lucjan Zarzycki',
    'Ludmił Tokarski',
    'Ludomił Kaczyński',
    'Ludolf Kulik',
    'Ludomir Mikołajczak',
    'Ludowit Szymczyk',
    'Ludwik Stańczyk',
    'Ładysław Biernat',
    'Łazarz Buczek',
    'Łucjan Węgrzyn',
    'Łukasz Zaremba',
    'Maciej Szostak',
    'Magnus Jurek',
    'Makary Maćkowiak',
    'Maksymilian Cichocki',
    'Malachiasz Gąsior',
    'Mamert Bartkowiak',
    'Manfred Bogusz',
    'Manuel Strzelecki',
    'Marcel Skowron',
    'Marceli Janiak',
    'Marcin Szczygieł',
    'Marcjan Janus',
    'Marek Gawron',
    'Marian Filipiak',
    'Marin Pałka',
    'Mariusz Cichoń',
    'Maryn Kula',
    'Mateusz Kaleta',
    'Maurycjusz Cieśla',
    'Maurycy Kostrzewa',
    'Maurycjusz Książek',
    'Medard Kubik',
    'Melchior Kucharczyk',
    'Metody Bartczak',
    'Michał Niewiadomski',
    'Mieszko Frączek',
    'Mieczysław Bagiński',
    'Mikołaj Rakowski',
    'Milan Rzepka',
    'Miłobąd Różycki',
    'Miłogost Malec',
    'Miłomir Sienkiewicz',
    'Miłorad Zaręba',
    'Miłosław Banasiak',
    'Miłosz Królikowski',
    'Miłowan Antczak',
    'Miłowit Gawlik',
    'Mirod Trzciński',
    'Miroład Żebrowski',
    'Miron Rogala',
    'Mirosław Mikulski',
    'Mirosz Rojek',
    'Modest Rogalski',
    'Mojmierz Grzegorczyk',
    'Mojmir Kisiel',
    'Mojżesz Borek',
    'Mściwoj Tkaczyk',
    'Murat Gawroński',
    'Myślimir Ślusarczyk',
    'Napoleon Hajduk',
    'Narcyz Witczak',
    'Nasif Lach',
    'Natan Stec',
    'Natanael Trojanowski',
    'Nataniel Dobosz',
    'Nestor Rybicki',
    'Nicefor Maliszewski',
    'Niecisław Długosz',
    'Nikodem Wąsik',
    'Norbert Pawelec',
    'Norman Kmiecik',
    'Odo Radomski',
    'Odon Gałązka',
    'Oktawian Kaczorowski',
    'Oktawiusz Grzesiak',
    'Olaf Wnuk',
    'Oleg Walkowiak',
    'Olgierd Bogucki',
    'Omar Zaborowski',
    'Onufry Białas',
    'Oskar Sokół',
    'Orian Bochenek',
    'Otniel Frąckowiak',
    'Oswald Wolny',
    'Otokar Zygmunt',
    'Otto Kwaśniewski',
    'Otton Żmuda',
    'Owidiusz Karwowski',
    'Pabian Lipski',
    'Pafnucy Wójcicki',
    'Pakosław Juszczak',
    'Pankracy Mika',
    'Paskal Pietras',
    'Patrycjusz Frankowski',
    'Patryk Nawrot',
    'Paweł Mroczek',
    'Pelagiusz Janas',
    'Petroniusz Więckowski',
    'Piotr Gaweł',
    'Placyd Cichy',
    'Polikarp Rosiak',
    'Prokop Jędrzejczyk',
    'Prot Skrzypek',
    'Protazy Lasota',
    'Przemysł Łapiński',
    'Przemysław Kołodziejski',
    'Przedpełk Dudziński',
    'Przybysław Krysiak',
    'Radogost Misiak',
    'Radomił Karaś',
    'Radomir Fijałkowski',
    'Radosław Wojtczak',
    'Radowit Bujak',
    'Radzimir Wroński',
    'Rafał Gruszczyński',
    'Rajmund Piórkowski',
    'Rajner Borowiec',
    'Remigiusz Kubacki',
    'Renat Burzyński',
    'Robert Piwowarczyk',
    'Roch Szafrański',
    'Roderyk Gutowski',
    'Roger Kałużny',
    'Roland Sołtys',
    'Roman Czyżewski',
    'Romeo Pasternak',
    'Romuald Dąbek',
    'Ronald Masłowski',
    'Rosłan Łukaszewski',
    'Rudolf Lisiecki',
    'Rufus Jagiełło',
    'Ryszard Łukasiewicz',
    'Rezi Stelmach',
    'Salomon Krakowiak',
    'Samir Jagodziński',
    'Sambor Szcześniak',
    'Samson Zajączkowski',
    'Samuel Tarnowski',
    'Sebastian Skoczylas',
    'Serafin Woźny',
    'Sergiusz Jędrzejczak',
    'Serwacy Zielonka',
    'Seweryn Filipek',
    'Sędomir Cygan',
    'Sędzisław Pakuła',
    'Siemowit Skibiński',
    'Sław Sobieraj',
    'Sławek Pilarski',
    'Sławomierz Jurkiewicz',
    'Sławomir Flis',
    'Sobiesław Bielawski',
    'Sofroniusz Drzewiecki',
    'Stanisław Kędziora',
    'Starwit Jakubiak',
    'Stefan Gąsiorowski',
    'Stoigniew Twardowski',
    'Stoisław Dębowski',
    'Stojan Guzik',
    'Strzeżymir Bober',
    'Subisław Wasiak',
    'Sulibor Bartosik',
    'Sulisław Falkowski',
    'Sykstus Mierzejewski',
    'Sylwan Strzelczyk',
    'Sylwester Cebula',
    'Sylwiusz Gołąb',
    'Symeon Majcher',
    'Syriusz Stanek',
    'Szczepan Kałuża',
    'Szymon Górniak',
    'Ścibor Wolak',
    'Świętibor Raczyński',
    'Świętomir Szwed',
    'Świętopełk Motyka',
    'Świętosław Kulig',
    'Tadeusz Góral',
    'Tarik Więcek',
    'Telesfor Bilski',
    'Teobald Grzywacz',
    'Teodor Matuszak',
    'Teodozjusz Nowaczyk',
    'Teofil Cholewa',
    'Tęgomir Kubica',
    'Tobiasz Stolarczyk',
    'Tomasz Wilczek',
    'Tomisław Drozdowski',
    'Tristan Bury',
    'Tulimir Rusin',
    'Tulimierz Krupiński',
    'Tymon Kopczyński',
    'Tymoteusz Michałek',
    'Tytus Misztal',
    'Urban Florek',
    'Ursyn Czapla',
    'Wacław Wojtas',
    'Wahid Jaśkiewicz',
    'Waldemar Kaszuba',
    'Walenty Kępa',
    'Walentyn Ruciński',
    'Walerian Bielak',
    'Walery Kuchta',
    'Walid Jankowiak',
    'Walter Malicki',
    'Wandelin Pytel',
    'Wawrzyniec Biały',
    'Więcesław Prokop',
    'Wenancjusz Kapusta',
    'Wendelin Gałka',
    'Wespazjan Andrzejczak',
    'Wielisław Skóra',
    'Wiesław Kaczmarski',
    'Wiktor Zagórski',
    'Wilhelm Siedlecki',
    'Wincenty Płonka',
    'Wirgiliusz Modzelewski',
    'Wirginiusz Słowiński',
    'Wisław Ciszewski',
    'Wit Milczarek',
    'Witold Staszewski',
    'Witołd Janusz',
    'Witosław Świerczyński',
    'Władysław Bożek',
    'Włodzimierz Zwoliński',
    'Włodzisław Gwóźdź',
    'Wojciech Kuc',
    'Wolimir Paczkowski',
    'Wojsław Partyka',
    'Wrocisław Sieradzki',
    'Wszebor Stępniak',
    'Zachariasz Bieńkowski',
    'Zbigniew Stachura',
    'Zdzisław Sochacki',
    'Zenobiusz Szyszka',
    'Zefir Dubiel',
    'Zefiryn Maślanka',
    'Zenon Jurkowski',
    'Ziemowit Pawlikowski',
    'Zwinisław Woś',
    'Zygfryd Jezierski',
    'Zygmunt Kolasa',
    'Zygmunta Urbańczyk',
    'Żarek Olczak',
    'Żarko Sławiński',
    'Żelisław Majka',
    'Żytomir Sitek',
    'Paweł Chmura',
    'Michał Szczerba',
    'Bronisław Dziuba',
    'Tadeusz Dec',
    'Amadeusz Koza',
    'Wiktor Kiełbasa',
    'Zachary Tokarz',
    'Otto Lipka',
    'Orfeusz Kita',
];
const femaleNameSurname = [
    'Abigail Nowak',
    'Ada Kowalska',
    'Adamina Wiśniewska',
    'Adela Wójcik',
    'Adelajda Kowalczyk',
    'Adriana Kamińska',
    'Adrianna Lewandowska',
    'Agata Zielińska',
    'Agnieszka Szymańska',
    'Agrypina Woźniak',
    'Afra Dąbrowska',
    'Aida Kozłowska',
    'Aisza Jankowska',
    'Ajna Wojciechowska',
    'Alberta Kwiatkowska',
    'Albertyna Mazur',
    'Albina Krawczyk',
    'Aldona Kaczmarek',
    'Aleksa Piotrowska',
    'Aleksandra Grabowska',
    'Aleksja Pawłowska',
    'Alfreda Michalska',
    'Alicja Zając',
    'Alida Król',
    'Alina Jabłońska',
    'Alojza Wieczorek',
    'Amalia Nowakowska',
    'Amanda Wróbel',
    'Amber Majewska',
    'Amelia Stępień',
    'Amina Olszewska',
    'Amira Jaworska',
    'Ana Malinowska',
    'Anastazja Adamczyk',
    'Andrea Górska',
    'Andrzeja Nowicka',
    'Andżelika Pawlak',
    'Aneta Dudek',
    'Angela Witkowska',
    'Angelika Walczak',
    'Angelina Rutkowska',
    'Aniela Sikora',
    'Anita Michalak',
    'Anna Szewczyk',
    'Antonina Ostrowska',
    'Anzelma Baran',
    'Apollona Tomaszewska',
    'Apollina Pietrzak',
    'Apolonia Wróblewska',
    'Arabella Marciniak',
    'Ariadna Zalewska',
    'Arleta Jasińska',
    'Arnolda Jakubowska',
    'Astryda Zawadzka',
    'Atena Sadowska',
    'Augusta Włodarczyk',
    'Augustyna Bąk',
    'Aurelia Borkowska',
    'Aurora Chmielewska',
    'Babeta Duda',
    'Balbina Szczepańska',
    'Barbara Wilk',
    'Bartłomieja Sokołowska',
    'Beata Sawicka',
    'Beatrycja Lis',
    'Beatrycze Kucharska',
    'Beatryksa Maciejewska',
    'Benedykta Kubiak',
    'Beniamina Kalinowska',
    'Berenika Wysocka',
    'Bernarda Mazurek',
    'Bernadeta Kaźmierczak',
    'Berta Kołodziej',
    'Betina Czarnecka',
    'Bianka Sobczak',
    'Bibiana Urbańska',
    'Blanka Sikorska',
    'Błażena Krajewska',
    'Bogdana Ziółkowska',
    'Bogna Zakrzewska',
    'Boguchwała Głowacka',
    'Bogumiła Krupa',
    'Bogusława Laskowska',
    'Bojana Wasilewska',
    'Bolesława Gajewska',
    'Bona Szymczak',
    'Bożena Makowska',
    'Bromira Przybylska',
    'Bronisława Mróz',
    'Brunhilda Brzezińska',
    'Brygida Błaszczyk',
    'Cecylia Baranowska',
    'Celestyna Szulc',
    'Celina Kaczmarczyk',
    'Cezaria Borowska',
    'Cezaryna Szczepaniak',
    'Chociemira Górecka',
    'Chwalisława Adamska',
    'Ciechosława Kania',
    'Ciesława Chojnacka',
    'Cinosława Leszczyńska',
    'Cina Janik',
    'Czesława Czerwińska',
    'Dajmira Mikołajczyk',
    'Dagna Andrzejewska',
    'Dagmara Kowalewska',
    'Dalia Wesołowska',
    'Dalila Lipińska',
    'Dalmira Cieślak',
    'Damroka Mucha',
    'Dana Konieczna',
    'Daniela Jarosz',
    'Danisława Zięba',
    'Danuta Kozak',
    'Dargomira Kozioł',
    'Dargosława Kowalik',
    'Daria Musiał',
    'Dąbrówka Kołodziejczyk',
    'Delfina Markowska',
    'Delia Brzozowska',
    'Diana Domańska',
    'Dilara Kopeć',
    'Dobiesława Tomczyk',
    'Domasława Tomczak',
    'Dominika Orłowska',
    'Donata Pawlik',
    'Dorosława Nowacka',
    'Dorota Ciesielska',
    'Dyzma Wawrzyniak',
    'Dżanan Piątek',
    'Dżamila Żak',
    'Dżesika Kurek',
    'Edeltruda Wolska',
    'Edyta Markiewicz',
    'Eleonora Wójtowicz',
    'Eliza Polak',
    'Elwira Kot',
    'Elżbieta Kruk',
    'Elmira Stankiewicz',
    'Emanuela Jastrzębska',
    'Emilia łuczak',
    'Emina Stasiak',
    'Emma Urbaniak',
    'Ernesta Wierzbicka',
    'Ernestyna Karpińska',
    'Eryka Sowa',
    'Estera Nawrocka',
    'Eugenia Piasecka',
    'Ewa Czajkowska',
    'Ewelina Sosnowska',
    'Fabia Bednarek',
    'Fabiana Janicka',
    'Fabiola Bielecka',
    'Farida Klimek',
    'Fatima Dziedzic',
    'Fatma Stefańska',
    'Faustyna Gajda',
    'Felicja Milewska',
    'Felicjana Jóźwiak',
    'Felicyta Majchrzak',
    'Feliksa Madej',
    'Ferdynanda Leśniak',
    'Filipa śliwińska',
    'Filipina Maj',
    'Flora Małecka',
    'Florentyna Skiba',
    'Floriana Kowal',
    'Franciszka Dobrowolska',
    'Fryderyka Socha',
    'Gabriela Bednarczyk',
    'Gaja Matuszewska',
    'Genowefa Olejniczak',
    'Gerarda Urban',
    'Gertruda Romanowska',
    'Gizela Marek',
    'Gloria Kasprzak',
    'Gniewomira Wilczyńska',
    'Gracja Wrona',
    'Gracjana Ratajczak',
    'Grażyna świątek',
    'Greta Michalik',
    'Gryzelda Domagała',
    'Grzymisława Grzelak',
    'Gustawa Pająk',
    'Gwidona Owczarek',
    'Hadriana Orzechowska',
    'Halina Kurowska',
    'Halszka Olejnik',
    'Hanna Sobolewska',
    'Hedwiga łukasik',
    'Helena Barańska',
    'Helga Kędzierska',
    'Henrieta Bukowska',
    'Henryka Matusiak',
    'Herma Mazurkiewicz',
    'Hermana Kosińska',
    'Hermenegilda Rogowska',
    'Hermina Skowrońska',
    'Hestia Sobczyk',
    'Hiacynta Marcinkowska',
    'Hilaria Lisowska',
    'Hildegarda Zych',
    'Hipolit świderska',
    'Honorata Bednarska',
    'Hortensja Chrzanowska',
    'Huberta Marszałek',
    'Husaria Morawska',
    'Ida Rybak',
    'Idosława Bednarz',
    'Idzia Janiszewska',
    'Idalia Kozieł',
    'Idzisława Kuczyńska',
    'Iga Kasprzyk',
    'Ildefonsa Sroka',
    'Ilia Białek',
    'Iliana Muszyńska',
    'Ilona Grzybowska',
    'Ilza Jędrzejewska',
    'Inga Marczak',
    'Ingeborga Kwiecień',
    'Ingryda Chmiel',
    'Irena Osińska',
    'Iryda Krzemińska',
    'Iwa Turek',
    'Iwona Małek',
    'Izabela Kubicka',
    'Izolda Czajka',
    'Izydora Paluch',
    'Jadwiga Pluta',
    'Jago Witek',
    'Jana Przybysz',
    'Janina Janowska',
    'Jarmiła Piekarska',
    'Jaromiła Biernacka',
    'Jaromira Gołębiewska',
    'Jarosława Stefaniak',
    'Jasława Marzec',
    'Jaśmina Michałowska',
    'Joachima Żukowska',
    'Joanna Staniszewska',
    'Jolanta Szydłowska',
    'Jowita Kaczor',
    'Józefa Podgórska',
    'Józefina Rudnicka',
    'Judyta Kulesza',
    'Julia Kacprzak',
    'Julianna Smolińska',
    'Julisława Lech',
    'Julita Serafin',
    'Justyna Kujawa',
    'Juta śliwa',
    'Kaja Czaja',
    'Kalina Lewicka',
    'Kamila Murawska',
    'Karima Dębska',
    'Karina Stachowiak',
    'Karola Popławska',
    'Karolina Góra',
    'Karyna Piątkowska',
    'Katarzyna Pietrzyk',
    'Kasandra Sowińska',
    'Kazimiera Rosińska',
    'Kiara Klimczak',
    'Kiliana Banaś',
    'Kinga Gołębiowska',
    'Kira Matysiak',
    'Klara Augustyniak',
    'Klarysa Karczewska',
    'Klaudia Czech',
    'Klaudyna Żurek',
    'Klementyna Banach',
    'Kleopatra Cieślik',
    'Klotylda Komorowska',
    'Konstancja Żurawska',
    'Kordula Zawada',
    'Kornelia Godlewska',
    'Koryna Grochowska',
    'Krystiana Niemiec',
    'Krystyna Rak',
    'Krzysztofa Szczęsna',
    'Ksawera Czyż',
    'Ksenia Bieniek',
    'Kunegunda Skrzypczak',
    'Kwiatosława Różańska',
    'Kwietosława Kuś',
    'Laila Winiarska',
    'Lajla Górka',
    'Lana Gruszka',
    'Larisa Cybulska',
    'Larysa Leśniewska',
    'Latifa Mielczarek',
    'Laura Krawiec',
    'Laurenjca Panek',
    'Lea Szczepanik',
    'Lejla Mikołajczak',
    'Lena Zarzycka',
    'Leokadia Ptak',
    'Leona Graczyk',
    'Leonarda Krzyżanowska',
    'Leoncja Siwek',
    'Leonora Słowik',
    'Leopolda Młynarczyk',
    'Lidia Drozd',
    'Ligia Przybyła',
    'Lilia Cichocka',
    'Liliana Maćkowiak',
    'Linda Konopka',
    'Liwia Strzelecka',
    'Lora Gil',
    'Luborada Kulik',
    'Lucjana Bartkowiak',
    'Lucjola Janiak',
    'Lucyna Tokarska',
    'Ludmiła Szymczyk',
    'Ludolfa Buczek',
    'Ludwika Kaczyńska',
    'Ludwina Kostrzewa',
    'Luiza Zaremba',
    'Luna Biernat',
    'Lilianna Stańczyk',
    'Ładana Skowron',
    'Ładysława Kłos',
    'Łagoda Bogusz',
    'Łucja Szostak',
    'Macieja Filipiak',
    'Magda Niewiadomska',
    'Magdalena Banasiak',
    'Maja Janus',
    'Maksa Grzyb',
    'Maksyma Węgrzyn',
    'Malina Górna',
    'Malwina Cichoń',
    'Małgorzata Gąsior',
    'Manuela Jurek',
    'Marcela Rakowska',
    'Marcelina Antczak',
    'Marcjana Bartczak',
    'Marcjanna Szczygieł',
    'Maria Królikowska',
    'Mariam Gawron',
    'Marianna Żebrowska',
    'Marietta Cieśla',
    'Marika Kubik',
    'Mariola Kaleta',
    'Marlena Różycka',
    'Marta Książek',
    'Martyna Kucharczyk',
    'Maryja Sienkiewicz',
    'Maryla Bagińska',
    'Maryna Trzcińska',
    'Marzena Zaręba',
    'Matylda Kula',
    'Melania Witczak',
    'Michalina Pałka',
    'Mieczysława Gawlik',
    'Milena Mikulska',
    'Milomira Gawrońska',
    'Miłosława Trojanowska',
    'Miłowita Rogalska',
    'Minerwa Rogala',
    'Mina Grzegorczyk',
    'Mira Rojek',
    'Mirabela Tkaczyk',
    'Miranda Radomska',
    'Mirela Maliszewska',
    'Miriam Rzepka',
    'Mirka Malec',
    'Miroda Rybicka',
    'Mirołada Kaczorowska',
    'Mirosława Dobosz',
    'Mojmira Hajduk',
    'Monika Gałązka',
    'Morzana Bogucka',
    'Morzena Borek',
    'Nadia Frączek',
    'Nadzieja Więckowska',
    'Najmiła Frankowska',
    'Najsława Długosz',
    'Narcyza Stec',
    'Natalia Lach',
    'Natasza Kmiecik',
    'Nela Zaborowska',
    'Nika Kisiel',
    'Nikodema Rosiak',
    'Nikola Grzesiak',
    'Nikita ślusarczyk',
    'Nikoleta Wojtczak',
    'Nina Kwaśniewska',
    'Noemi Kubacka',
    'Nora Pietras',
    'Norberta Wąsik',
    'Norma Juszczak',
    'Oda Karwowska',
    'Odeta Mika',
    'Odyla Frąckowiak',
    'Ofelia Lasota',
    'Oksana Wójcicka',
    'Oktawia Walkowiak',
    'Ola Kołodziejska',
    'Olga Krysiak',
    'Olimpia Lipska',
    'Oliwia Burzyńska',
    'Oriana Nawrot',
    'Ota Wrońska',
    'Otylia Jędrzejczyk',
    'Ożanna Białas',
    'Olena Mroczek',
    'Pabiana Sokół',
    'Pamela Fijałkowska',
    'Patrycja Wnuk',
    'Paula Dudzińska',
    'Paulina Szafrańska',
    'Pelagia Skrzypek',
    'Petra Pawelec',
    'Petronela Zajączkowska',
    'Petronia Janas',
    'Placyda Bochenek',
    'Pola Zygmunt',
    'Polmira Gruszczyńska',
    'Przemysława Krakowiak',
    'Przybysława Lisiecka',
    'Rachela łukasiewicz',
    'Ramona Jagodzińska',
    'Radmiła Piórkowska',
    'Radomiła Borowiec',
    'Radomira Jędrzejczak',
    'Radosława Czyżewska',
    'Rafaela Masłowska',
    'Rajmunda Bujak',
    'Rajna Misiak',
    'Raszyda Piwowarczyk',
    'Rebeka Żmuda',
    'Regina Sobieraj',
    'Remigia Jurkiewicz',
    'Renata Dąbek',
    'Rita Pilarska',
    'Roberta Pasternak',
    'Rodzisława Twardowska',
    'Roksana Gaweł',
    'Roma łapińska',
    'Romana Skibińska',
    'Romualda Drzewiecka',
    'Rozalia Bielawska',
    'Rozalinda Jagiełło',
    'Rozamunda Bartosik',
    'Rozetta Gutowska',
    'Rozwita Szcześniak',
    'Róża łukaszewska',
    'Rudolfina Karaś',
    'Ruta Flis',
    'Ryszarda Stelmach',
    'Sabina Strzelczyk',
    'Safira Dębowska',
    'Salma Skoczylas',
    'Saloma Zielonka',
    'Salomea Kędziora',
    'Samanta Raczyńska',
    'Sandra Tarnowska',
    'Sara Jakubiak',
    'Sebastiana Pakuła',
    'Selena Mierzejewska',
    'Selma Kałuża',
    'Serafina Wasiak',
    'Seweryna Sołtys',
    'Sędomira Bober',
    'Sędzisława Krupińska',
    'Sława Bilska',
    'Sławina Cygan',
    'Sławomira Gąsiorowska',
    'Sobiesława Kubica',
    'Sonia Szwed',
    'Stamira Filipek',
    'Stanisława Majcher',
    'Stefania Górniak',
    'Stela Milczarek',
    'Stoisława Falkowska',
    'Stella Kałużna',
    'Sydney Staszewska',
    'Strzeżymira Stanek',
    'Subisława Góral',
    'Sulima Nowaczyk',
    'Sulisława Kopczyńska',
    'Sybilla Kaczmarska',
    'Sylwana Guzik',
    'Sylwia Stolarczyk',
    'Szarlota Słowińska',
    'Szarlin Ciszewska',
    'Szarlina Zwolińska',
    'Szejma Wilczek',
    'Szymona Więcek',
    'Świetlana Jaśkiewicz',
    'Świętomira Gołąb',
    'Świętosława Andrzejczak',
    'Tabita Rucińska',
    'Tacjana Zagórska',
    'Tadea Matuszak',
    'Tamara Jezierska',
    'Tatiana Kulig',
    'Tekla Drozdowska',
    'Telimena Wolak',
    'Teodora Rusin',
    'Teodozja Cebula',
    'Teresa Misztal',
    'Tęgomira Modzelewska',
    'Tina Siedlecka',
    'Tolisława Michałek',
    'Tomiła Grzywacz',
    'Tomisława Motyka',
    'Tulimira Olczak',
    'Tessa Sieradzka',
    'Ulana Malicka',
    'Ulryka Jackowska',
    'Uma Stachura',
    'Una Sławińska',
    'Unima Florek',
    'Urszula Kępa',
    'Uta Sochacka',
    'Wacława Cholewa',
    'Walentyna Paczkowska',
    'Waleria Pawlikowska',
    'Wanda Kaszuba',
    'Wanessa Bieńkowska',
    'Wera Jurkowska',
    'Weronika Czapla',
    'Wesna Bożek',
    'Wiara Świerczyńska',
    'Wielina Pytel',
    'Wiera Jankowiak',
    'Wierada Partyka',
    'Wiesława Wojtas',
    'Wiktoria Stępniak',
    'Wilhelmina Janusz',
    'Wilma Gałka',
    'Wincentyna Kuchta',
    'Wioleta Szyszka',
    'Wirgilia Rosa',
    'Wirginia Kuc',
    'Wisława Kwiecińska',
    'Witosława Dubiel',
    'Władysława Florczak',
    'Włodzimiera Bielak',
    'Wolimira Szczerba',
    'Wrocisława Szatkowska',
    'Zaida Skalska',
    'Zaira Kolasa',
    'Zdzisława Stanisławska',
    'Zefiryna Kruszewska',
    'Zenobia Prokop',
    'Zenona Skóra',
    'Zofia Woś',
    'Zoja Majka',
    'Zuzanna Broda',
    'Zwinisława Gwóźdź',
    'Zygfryda Kalinowskijska',
    'Zyta Grądeckowska',
    'Żaklina Gubałowskińska',
    'Żaneta Wilirmianowska',
    'Żanna Kroczowymska',
    'Żelisława Krędzianowska',
    'Żużanna Filipińska',
    'Żywia Randomimowska',
    'Żywisława Luleczkowska',
];
const mergedPeople = [...maleNameSurname, ...femaleNameSurname];

const displayingDomain = ["(EHALLUKS)", "(EXTERNAL)"];
const customDomain = "@ehalluks.com";
const m365License = ["E3", "E2", "E1"];

const organizationUnit = ["Groups", "EMEA", "PL", "EXP", "WAW"];

const persons = [];
const users = [];

const polishCharacters = ['ą', 'ć', 'ę', 'ł', 'ń', 'ó', 'ś', 'ź', 'ż'];
const basicCharacters = ['a', 'c', 'e', 'l', 'n', 'o', 's', 'z', 'z'];

const numberUsersToAdd = 150;

class NewUser {
    constructor(id, nameSurname, displayName, ldap, email, ou, m365, passwordExpires, startWorkDate){
        this.id = id;
        this.nameSurname = nameSurname;
        this.displayName = displayName;
        this.ldap = ldap;
        this.email = email;
        this.ou = ou;
        this.m365 = m365;
        this.passwordExpires = passwordExpires;
        this.startWorkDate = startWorkDate;
    };
}

//functions:
const getSomeNumber = number => {return Math.floor(Math.random() * number)}

const randomPerson = () => {

    return mergedPeople[getSomeNumber(1024)]
};
const randomDisplayingDomain = () => {

    return displayingDomain[getSomeNumber(displayingDomain.length)];
};
const randomOu = () => {

    const randomNumbers = [];

    while (randomNumbers.length < 3) {
        const randomNumber = Math.floor(Math.random() * 5);
        if (!randomNumbers.includes(randomNumber)) {
            randomNumbers.push(randomNumber);
        }
    }

    const [nr1, nr2, nr3] = randomNumbers;
    return `OU=${organizationUnit[nr1]}, OU=${organizationUnit[nr2]}, OU=${organizationUnit[nr3]}`;
};
const randomLicense = () => {

    return m365License[getSomeNumber(m365License.length)];
};

const createLdap = person => {

    const words = person.split(" ");
    const minLength = 6;
    const maxLength = 10;
    const shortNameLength = Math.floor(Math.random() * (maxLength - minLength + 1)) + minLength;

    let shortName = "";

    let i = 0;
    while (i < words.length && shortName.length < shortNameLength) {
        const word = words[i];

        if (word.length <= 3) {
            shortName += word;
        } else if (shortName.length + 3 <= shortNameLength) {
            shortName += word.slice(0, 3);
        } else if (shortName.length + word.length <= shortNameLength) {
            shortName += word.slice(0, shortNameLength - shortName.length);
        }

        i++;
    }

    let personWithOutPolishChar = shortName;
    for (let i = 0; i < polishCharacters.length; i++) {
        const regex = new RegExp(polishCharacters[i], 'g');
        personWithOutPolishChar = personWithOutPolishChar.replace(regex, basicCharacters[i]);
    }
    return personWithOutPolishChar.toLowerCase();
};

const generateRandomDate = () => {

    const startDate = new Date('2023-01-01').getTime();
    const endDate = new Date('2023-12-31').getTime();
    const randomTime = startDate + Math.random() * (endDate - startDate);
    const randomDate = new Date(randomTime);
    return randomDate.toISOString().slice(0, 10);
};

const generateRandomDateForPassword = startWork => {

    const passExpires = new Date(startWork);
    passExpires.setDate(passExpires.getDate() + 10);
    return passExpires.toISOString().slice(0, 10);
};

const replacePolishCharacters = person => {

    let personWithOutPolishChar = person;
    for (let i = 0; i < polishCharacters.length; i++) {
        const regex = new RegExp(polishCharacters[i], 'g');
        personWithOutPolishChar = personWithOutPolishChar.replace(regex, basicCharacters[i]);
    }
    return `${personWithOutPolishChar.toLowerCase().replace(/\s+/g, '.')}${customDomain}`;
};


const createNewUser = () => {

    for (let i= 0; i <= numberUsersToAdd;i++) {

        const id = uuid();
        const person = randomPerson();
        const displayPersonName = `${person} ${randomDisplayingDomain()}`;
        const ldapForNewPerson = createLdap(person).toLowerCase();
        const principalEmail = replacePolishCharacters(person)
        const ouGroups = randomOu();
        const microsoftLicense = randomLicense();
        const startWork = generateRandomDate();
        const passwordDateExpires = generateRandomDateForPassword(startWork);
        persons.push({id: id, name: person});

        users.push(new NewUser(id, person, displayPersonName, ldapForNewPerson, principalEmail, ouGroups, microsoftLicense, String(passwordDateExpires), String(startWork)));

    }

    for(let i=0; i < persons.length;i++) {
        for(let j=i+1; j< persons.length-1; j++) {
            if(persons[j].name === persons[i].name) {
                users.forEach((element, index) => {
                    if (element.id === persons[j].id) {
                        element.nameSurname = element.nameSurname + index
                        element.displayName = element.displayName.replace(/^(.*)\((.*)\)$/, (match, name, suffix) => `${name}${index} (${suffix})`)
                        element.email = element.email.replace(/@(.+)/, `${index}@$1`);
                        element.ldap = element.ldap + index
                    }
                })
            }
        }
    }

    //test sprawdzający wartości pola
    for (const prop in users) {
        if (users[prop] === undefined || users[prop] === null || users[prop] === "") {
            console.log(`Pole ${prop} jest niezdefiniowane lub ma wartość null lub pusty ciąg znaków.`);
        }
    }


};

createNewUser();

//masowe dodanie rekordow do bazy
(async()=> {

    const conn = await mysql.createConnection({
        host: "localhost",
        user: "root",
        database: "activedirectory",
    });

    const statement = await conn.prepare('INSERT INTO `adusers` VALUES(?,?,?,?,?,?,?,?,?)');

    try{
        for(const newPerson of users){
            await statement.execute(Object.values(newPerson));
        }
        console.log("działa");
    } finally {
        statement.close();
    }
    await conn.end();
})();

//SELECT * FROM adusers ORDER BY ldap ASC;
